# Generated by Django 3.2.9 on 2022-03-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0006_alter_vehiclepassport_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='motorpool/brands'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='options',
            field=models.ManyToManyField(related_name='cars', to='motorpool.Option', verbose_name='Опции'),
        ),
    ]
